#!/bin/bash
#**********************************************************************
#***                                                                ***
#*** Script:  mvs                                                   ***
#***                                                                ***
#*** Purpose: IPL OS/VS2-MVS 3.8j (TK4- unattended operations)      ***
#***                                                                ***
#*** Updated: 2014/12/22                                            ***
#***                                                                ***
#**********************************************************************
#
# set environment
#
export PATH=/opt/hercules/bin:$PATH
export LD_LIBRARY_PATH=/opt/hercules/lib:/opt/hercules/lib/hercules:$LD_LIBRARY_PATH
#
# source configuration variables
#
if [ -f local_conf/tk4-.parm ]; then . local_conf/tk4-.parm; fi
if [[ ${arch:0:3} == 'arm'   && $REP101A == '' ]];then export REP101A=specific;fi
if [[ $REP101A == 'specific' && $CMD101A == '' ]];then export CMD101A=02;fi
#
# IPL OS/VS2-MVS 3.8j
#
hercules -f conf/tk4-.cnf -r scripts/ipl.rc -o log/3033.log